[package]
name = "rust_hanabi"
version = "0.1.0"
authors = ["Jeff Wu <wuthefwasthat@gmail.com>"]

[dependencies]
rand = "*"
log = "*"
getopts = "0.2.19"
fnv = "*"
float-ord = "*"
crossbeam = "0.2.5"
csv = "1.1"
serde_derive = "1.0.97"
